---
- hosts: worker-machine
  vars:
    setup: bash -x setup.sh
  tasks:
    - name: "copy setup file"
      copy: src="../setup.sh" dest="{{ destination_path }}"
    - name: Setting up environment
      shell: "{{ setup }}"
      become: yes
    - name: Cleaning up
      shell: rm setup.sh
