---
- hosts: worker-machine
  gather_facts: no
  vars:
    setup: bash -x setup.sh
  tasks:
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: "copy setup file"
      copy: src="../setup.sh" dest="{{ destination_path }}"
    - name: Setting up environment
      shell: "{{ setup }}"
      become: yes
    - name: Cleaning up
      shell: rm setup.sh
